### ISSUE TITLE
Dynamic Text element doesn't offer option to select fields for dynamic text selection

### ISSUE THREAD

**Issue by sol1-matt** [meerkat-dashboard/meerkat#101]
The expected behaviour is you 

- Select **Visual Type: Dynamic Text**
- From **Icinga Host** select the host required
at this point a second drop down appears under **Icinga Host** which contains hosts properties that can be selected to fill out the value of the dymanic text

Actual behavior is
- Select **Visual Type: Dynamic Text**
- From **Icinga Host** select the host required
no second drop down appears.

**Comment by davekempe** [comment]
This works fine for me in my local test version. Please update to latest version and try again.

![image](https://user-images.githubusercontent.com/140519/183014465-7e6207f1-a750-4e20-83fd-de47b454d280.png)
