### ISSUE TITLE
Service Filter mode doesn't really work with Check Data Mode or Plugin Output for an Icinga Card

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#102]
What I think should happen / Bug Report:
- when you select "Service Filter" under "Icinga Host or Service" Meerkat should find 0,1 or several service results
- Zero results
-- color should be black
-- text should be something like "No Services Match" by default but could be configurable
-- plugin output should work and default to the default text
- One result
-- behaviour as for a single service
- Two or more results
-- color should be "worst" of matching services (or configurable to be "best" or "worst" or "majority" etc.)
-- text should be:
--- a line summarising the matching services; e.g. "3 services matching filter, 33% Critical, 33% Warning, 33% OK"
--- for each matching service:
---- A blank line
---- The name of the service
---- the service output
-- plugin output should work on the whole text as above

What actually happens / how to reproduce:
Option 1:
1. User sets up an Icinga Card with "Service" under "Icinga Host or Service"
2. User changes type to "Service Filter" and sets up the filter
3. Meerkat silently still uses the previously selected service for the text which goes to the plugin output regex, ignoring the service filter
Option 2:
1. User sets up an Icinga Card with "Service Filter" under "Icinga Host or Service"
2. There is no option for "Check Data Mode" / "Plugin Output"

**Comment by sol1-matt** [comment]
I think this falls under a larger issue in that elements and element behaviour needs a refactor so the saved json data is consistent (drop **id** and put everything in filters) and properties of elements work consistently between different element types and at different levels of returned data.

Both @s2156945 and I make dashboards do useful things that aren't specifically designed into meerkat. This refactor would codify that and solve bugs like the above.

**Comment by ollytom** [comment]
@sol1-matt and I did some debugging together. The bug probably lives
in useCheckCard() in frontend/src/elements/card.jsx. There is probably
some state passed in the `options` field of the given parameter that
needs to be cleared.

It's also worth noting that the way element options are represented in
Meerkat is getting a bit hairy. The backend `Option` struct contains
56 fields! Some fields apply to some elements and not to others:

```
type Option struct {
	Filter                          string `json:"filter"`
	ObjectType                      string `json:"objectType"`
	Selection                       string `json:"selection"`
	CheckID                         string `json:"checkId"`
	NameFontSize                    int    `json:"nameFontSize"`
	StatusFontSize                  int    `json:"statusFontSize"`
	RightArrow                      bool   `json:"rightArrow"`
	LeftArrow                       bool   `json:"leftArrow"`
	StrokeWidth                     int    `json:"strokeWidth"`
	Image                           string `json:"image"`
	OKSvg                           string `json:"okSvg"`
	OKStrokeAcknowledgedColor       string `json:"okStrokeAcknowledgedColor"`
	OKStrokeColor                   string `json:"okStrokeColor"`
	WarningAcknowledgedStrokeColor  string `json:"warningAcknowledgedStrokeColor"`
	WarningSvg                      string `json:"warningSvg"`
	UnknownAcknowledgedStrokeColor  string `json:"unknownAcknowledgedStrokeColor"`
	UnknownSvg                      string `json:"unknownSvg"`
	CriticalStrokeColor             string `json:"criticalStrokeColor"`
	CriticalAcknowledgedStrokeColor string `json:"criticalAcknowledgedStrokeColor"`
	CriticalSvg                     string `json:"criticalSvg"`
	CriticalImage                   string `json:"criticalImage"`
	CriticalAcknowledgedImage       string `json:"criticalAcknowledgedImage"`
	OkImage                         string `json:"okImage"`
	UnknownImage                    string `json:"unknownImage"`
	UnknownAcknowledgedImage        string `json:"unknownAcknowledgedImage"`
	WarningImage                    string `json:"warningImage"`
	WarningAcknowledgedImage        string `json:"warningAcknowledgedImage"`
	Svg                             string `json:"svg"`
	StrokeColor                     string `json:"strokeColor"`
	Source                          string `json:"source"`
	AudioSource                     string `json:"audioSource"`
	Text                            string `json:"text"`
	BackgroundColor                 string `json:"backgroundColor"`
	TextAlign                       string `json:"textAlign"`
	TextVerticalAlign               string `json:"textVerticalAlign"`
	FontColor                       string `json:"fontColor"`
	FontSize                        string `json:"fontSize"`
	ScrollPeriod                    string `json:"scrollPeriod"`
	LinkURL                         string `json:"linkURL"`
	OkSound                         string `json:"okSound"`
	WarningSound                    string `json:"warningSound"`
	UnknownSound                    string `json:"unknownSound"`
	CriticalSound                   string `json:"criticalSound"`
	UpSound                         string `json:"upSound"`
	DownSound                       string `json:"downSound"`
	MuteAlerts                      bool   `json:"muteAlerts"`
	CheckDataSelection              string `json:"checkDataSelection"`
	CheckDataPattern                string `json:"checkDataPattern"`
	CheckDataDefault                string `json:"checkDataDefault"`
	Dynamic                         bool   `json:"dynamic"`
	ID                              string `json:"id"`
	DynamicText                     string `json:"dynamicText"`
	DynamicText2                    string `json:"dynamicText2"`
	DynamicText2Structure           bool   `json:"dynamicText2Structure"`
	BoldText                        bool   `json:"boldText"`
}
    Option contains element options
```

The frontend components pass around a corresponding `options` object
in each call to `useCheckCard()`. The bug probably is in logic around
setting, unsetting, resetting those object properties, and which ones
to prioritise.

One way to refactor is to have more elements and fewer options. A
quick but not very good example: instead of just having an icinga card
element, you could have an icinga host and icinga service card
elements.

**Comment by sol1-matt** [comment]
> One way to refactor is to have more elements and fewer options. A
> quick but not very good example: instead of just having an icinga card
> element, you could have an icinga host and icinga service card
> elements.

I'm not sure what you think the difference is between a host and service element. 
The result data behind them is essentially the same. You might need to explain this one to me.

There is a different in result data when you have 0, 1 or multiple results though but one problem is number of results can change over time, when you setup the element it might have 1 result and latter on it could have 0 or multiple results.

The frontend has elements that are used for specific purposes eg: display video, display static text, display status and text from result, display image and status. If we split things up with more elements based on the incoming data it could get really complex for the user.

There is also a long term goal to support multiple backends. It could be a particular backend needs a specific element type to make sense, but I think a cleaner implementation will be abstraction with multiple backends feeding data into a intermediate format that is consumed by frontend elements.

100% agree the current list of options is messy though, a better way to manage/clean them up would be valuable.

**Comment by ollytom** [comment]
Options were not reliably cleared when elements and element options were set. For example, if you changed an element from a SVG icon to a clock, the element would still have many irrelevant options set.
That would have been at least one part of the bug. This is fixed now.

Another source of this bug would have been how the server received requests from the UI for this data. Sometimes it got the name of an object, sometimes a filter expression (even if one object was implicitly desired).
There was a lot of juggling between these requests on the server. Some data from the Icinga API was returned and some not. Results were serialised/deserialised differently.
This is resolved; the server now just proxies requests to Icinga.

Another complication probably contributing factor to this bug: if certain element options were set requests would still be made even though nothing was meant to be rendered. If I remember rightly, if a URL to a video was set, the browser would still request the video even though the element had changed to a text element some time ago.
This is fixed now: the (p)react components making up the elements is significantly smaller so bugs like this were obvious to see and have been fixed on the way to v3 https://github.com/meerkat-dashboard/meerkat/milestone/1

The current development of this feature is being tracked in #132.
