### ISSUE TITLE
Unify all Elements to behave in a consistent manner from both the GUI and config

### ISSUE THREAD

**Issue by sol1-matt** [meerkat-dashboard/meerkat#104]
## Is your feature request related to a problem? Please describe.
This request covers multiple bugs as well as unsupported features. As such it is a request to unify behavior of dashboard elements by refactoring the code rather than fixing a individual issue which may result in more inconsistency.

## Describe the solution you'd like
**Unify element source storage**
All elements have a single json field, or linked json fields, which are used to specify the source of results.
Fields currently in use are `id`, [`objectType`, `filter`, `selection` (perhaps)].
`selection` has a lot of redundancy in values, `service-filter` could be a `service` or `service-group`. Selection seems redundant except for storing GUI state.
Related to #102

**Unify visual element management**
Multiple fields have different options for management of the visual look and feel. The manipulation of look and feel in a dashboard should be element agnostic where appropriate.
eg: 
Icinga Cards allow for the setting of font size.
Dynamic text allows for the setting of font size, background colour and font colour. 
Static text allows for the setting of font size, font weight (bold), background colour and font colour. 
Icinga SVG allows for the setting of the color for each state.

The ideal outcome would be a simple logic tree with things like
```
if element has text:
   add all text editing options;
if element returns state: 
   add color changing options;
```

**Unify available data management**
Like visual element management returned data is handled differently. Meerkat can be 'tricked' into using available data elements via editing the saved json file which results in useful functionality, eg: Default value on a service group with a Icinga card = State colour changing label.

Dynamic text allows you to access fields set on the host.
Icinga Cards allow you to result strings and perfdata.

The current behavior is that the GUI only offers options that exist. But it could be the option, eg a specific perf data value, doesn't exit now but may later. So the ideal solution would be one that not only allows for adding values offered but values that could be offered in the future.

There is also the possibility of a service only being able to return 0 or 1 checks or 0 or many results. How the above is managed with these single or multiple result should be considered.

**Comment by ollytom** [comment]
There are now 3 options:

- objectName (e.g. “www.example.com!ping”)
- objectType (e.g. “service-group”), see also #143 
- objectAttr (e.g. “name” or “attrs.last_check_result.state”), see #132 

and 3 elements:

- card
- line
- icon

I can’t remember how many other options and elements there were before.
Just did a quick search and found these:

- id
- checkId
- objectName
- objectType
- filter
- dynamic
- dynamicText
- dynamicText2
- selection
- dynamicText2Structure

.. yep..

Work on #149 is ongoing
