### ISSUE TITLE
Docker Compose file?

### ISSUE THREAD

**Issue by brusilva84** [meerkat-dashboard/meerkat#105]
Where can I find the docker-compose.yml file you mention on the docs?

**Comment by davekempe** [comment]
hey @MC-brunomendes 
We removed the docker-compose file as we wanted to stop supporting it and none of the devs use it and it didn't make sense anyway.
Covered in this pull-request: https://github.com/meerkat-dashboard/meerkat/pull/80

Meerkat is really easier in just a single docker container, and I believe some of the devs use that for dev work.

**Comment by ollytom** [comment]
We've added a Dockerfile (https://github.com/meerkat-dashboard/meerkat/blob/main/Dockerfile).
We'd like to publish the images to GitHub's container registry. But we don't have a workflow yet!
If you've got any tips or advice please let us know in https://github.com/meerkat-dashboard/meerkat/issues/138. Thanks! :)
