### ISSUE TITLE
Redundancy in values of selection attribute in an Element

### ISSUE THREAD

**Issue by ollytom** [meerkat-dashboard/meerkat#113]
From @sol1-matt  in #104:

> All elements have a single json field, or linked json fields, which are used to specify the source of results. Fields currently in use are `id`, [`objectType`, `filter`, `selection` (perhaps)]. `selection` has a lot of redundancy in values, `service-filter` could be a `service` or `service-group`. Selection seems redundant except for storing GUI state.
> Related to #102

It would be helpful to get an example JSON snippet showing this
redundancy in an element's on-disk representation. Can we get one
uploaded here? Thanks!

**Comment by sol1-matt** [comment]
This is from a service filter, the `id` wrong but still used for something.
```
        "id": "host_example1!APservice_example1",
        "objectType": "service",
        "filter": "service.__name==\"host_example1!Nick Sonic SD A\"||service.name==\"host_example1!ping\"",
        "selection": "service-filter",

```

This is from a service, the `id` and `filter` are the same data. 
Also `filter` value is a icinga service filter so `selection` of **service** is redundant in the sense every request is a filter for host or service.
```
        "objectType": "service",
        "filter": "service.__name==\"host_example2!ping\"",
        "selection": "services",
        "id": "host_example2!ping",

```

This is a service filter using **match** which is a search function of the icinga api, it can return 0 to many results.
Again `id` is incorrect but it is also used for things, particularly in editing.
```
        "id": "host_example3 - service_example2",
        "objectType": "service",
        "filter": "match(\"*service_example2\",service.name)&&host.name==\"host_example3\"",
        "selection": "service-filter",
```

This is a service group which can return 0 to many results
```
        "objectType": "service",
        "filter": "\"Multicast A\" in service.groups",
        "selection": "service-groups",
        "id": "Multicast A"
```

**Comment by ollytom** [comment]
Specifying an icinga object has been consolidated to one element option named `objectName`.
