### ISSUE TITLE
Adding URL to static text box pushes down text

### ISSUE THREAD

**Issue by stevenahmet** [meerkat-dashboard/meerkat#115]
**Describe the bug**
If you have a static text box, and you add a URL link to the box, the text inside the box gets pushed down, almost like the text disappears.

**To Reproduce**
1. Add a static text box
2. Keep the text box small, ie to the size of the text
3. Save and view. You should see your text.
4. Now go back and edit the box and add a URL link.
5. Save and view and the text will "disappear:.

**Expected behavior**
Your text shouldn't move if you add a URL link

**Screenshots**

**Desktop (please complete the following information):**
 - Any OS
 - Any browser
 - ??

**Additional context**
Showed Matt Smith. He mentioned maybe the CSS is pushing the text down unexpectedly.

**Comment by ollytom** [comment]
Ah yes, reliably can reproduce this one. Thanks for those steps!
Let me do a bit of fiddling to try and find out what's going on.

**Comment by ollytom** [comment]
A test dashboard to reproduce:

	{
	    "title": "test",
	    "tags": [],
	    "background": null,
	    "elements": [
	        {
	            "type": "static-text",
	            "title": "link",
	            "rect": {
	                "x": 2.7027027027027026,
	                "y": 2.433628318584071,
	                "w": 58.25825825825825,
	                "h": 22.566371681415927
	            },
	            "options": {
	                "objectType": null,
	                "filter": null,
	                "selection": "",
	                "nameFontSize": 40,
	                "statusFontSize": 60,
	                "muteAlerts": false,
	                "text": "Hello world!",
	                "fontSize": "22",
	                "fontColor": "#ffffff",
	                "textAlign": "center",
	                "textVerticalAlign": "center",
	                "backgroundColor": "#007bff",
	                "linkURL": "http://example.com"
	            }
	        },
	        {
	            "type": "static-text",
	            "title": "nolink",
	            "rect": {
	                "x": 3.003003003003003,
	                "y": 25.995575221238937,
	                "w": 57.507507507507505,
	                "h": 25.221238938053098
	            },
	            "options": {
	                "objectType": null,
	                "filter": null,
	                "selection": "",
	                "nameFontSize": 40,
	                "statusFontSize": 60,
	                "muteAlerts": false,
	                "text": "Hello world!",
	                "fontSize": "22",
	                "fontColor": "#ffffff",
	                "textAlign": "center",
	                "textVerticalAlign": "center",
	                "backgroundColor": "#007bff",
	                "boldText": false
	            }
	        }
	    ],
	    "globalMute": true,
	    "variables": {},
	    "okSound": "/dashboards-data/ok.mp3",
	    "criticalSound": "/dashboards-data/critical.mp3",
	    "warningSound": "/dashboards-data/warning.mp3",
	    "unknownSound": "/dashboards-data/unknown.mp3",
	    "upSound": "/dashboards-data/up.mp3",
	    "downSound": "/dashboards-data/down.mp3"
	}

The thing I noticed is that in the rendered HTML, elements with a link have the `justify-content: center;` style set inline,
but this is ignored because they are not in a flex container.

Relevant CSS:

	element {
	  height: 100%;
	  font-size: 22px;
	  background-color: rgb(0, 123, 255);
	  color: rgb(255, 255, 255);
	  justify-content: center;
	  align-items: center;
	  text-align: center;
	  line-height: 470%;
	}

Adding `display: flex` manually causes the expected result: the text is justified in the center of the element.
There's some nesting of divs which happens when we add a link that causes us to lose the flex container somehow;
elements with no link are in a flex container by default.

**Comment by davekempe** [comment]
Ah I had this in cards without a URL at certain sizes last week too btw. So I suspect this will fix a few things at once.

**Comment by ollytom** [comment]
Ok got the specific problem. The flex container is only applied to direct text child elements of the check class:
	
	.check > .text {
		white-space: pre;
		display: flex;
	}

When we add a link, the rendered HTML results in the direct child elements to be `a` elements.

	<div class="check" style="left: 2.7027%; top: 2.43363%; width: 58.2583%; height: 22.5664%; transform: rotate(0rad);">
		<a id="a-link" href="http://example.com">
			<a id="text-link" href="http://example.com">
				<div class="check-content text" style="height: 100%; font-size: 22px; background-color: rgb(0, 123, 255); color: rgb(255, 255, 255); justify-content: center; align-items: center; text-align: center; line-height: 470%;">Hello world!
				</div>
			</a>
		</a>
	</div>

I'm close to the limit of my CSS abilities here! But I should be able to work out a neat way of expressing the element relationship without any major changes!
Maybe if we're lucky we might have a net reduction in the number of lines of code...

**Comment by ollytom** [comment]
The "linking URL" patch made in commit b2fc23b124b8416 could have done with some code review at the time :(

**Comment by stevenahmet** [comment]
Thanks for fixing that. So now that's been fixed, how do I upgrade Meerkat? :)

**Comment by davekempe** [comment]
> Thanks for fixing that. So now that's been fixed, how do I upgrade Meerkat? :)

There has been massive changes which we are working through testing. Please hold off until we have completed the current round of testing and bug fixing.
once thats done, installing the deb file over the top of the old one should just work though.

**Comment by stevenahmet** [comment]
> > Thanks for fixing that. So now that's been fixed, how do I upgrade Meerkat? :)
> 
> There has been massive changes which we are working through testing. Please hold off until we have completed the current round of testing and bug fixing. once thats done, installing the deb file over the top of the old one should just work though.

Thanks Dave

**Comment by stevenahmet** [comment]
Hi. How has the testing been going? Can I upgrade Meerkat yet? There are other issues that I'm seeing.

From: Dave Kempe ***@***.***>
Sent: Tuesday, 1 November 2022 9:43 AM
To: meerkat-dashboard/meerkat ***@***.***>
Cc: Steven Ahmet (SYD) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [meerkat-dashboard/meerkat] Adding URL to static text box pushes down text (Issue #115)


Thanks for fixing that. So now that's been fixed, how do I upgrade Meerkat? :)

There has been massive changes which we are working through testing. Please hold off until we have completed the current round of testing and bug fixing.
once thats done, installing the deb file over the top of the old one should just work though.

-
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmeerkat-dashboard%2Fmeerkat%2Fissues%2F115%23issuecomment-1297779929&data=05%7C01%7Csteven.ahmet%40foxsports.com.au%7C69b526a40d9c4f15d9ca08dabb915029%7C55e0963ce2f2477cad98ba2d1be5ae2b%7C1%7C0%7C638028530047232334%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bu411OIOEDsIjRMufze9szsi4zme%2B%2BMnCWVnWlYSi%2B0%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKWNGKPUCHFWJGRP4ORLOO3WGBDQPANCNFSM567RRUAA&data=05%7C01%7Csteven.ahmet%40foxsports.com.au%7C69b526a40d9c4f15d9ca08dabb915029%7C55e0963ce2f2477cad98ba2d1be5ae2b%7C1%7C0%7C638028530047232334%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TWGRnRpsgR8iyy0xoWRcbdxfSRJkRuQZ9%2BIBF2y9EHA%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

This e-mail, and any attachment, is confidential. If you are not the intended recipient, please delete it from your system, do not use or disclose the information in any way, and notify the sender immediately. Any views expressed in this message are those of the individual sender and may not be the views of Foxtel, unless specifically stated. No warranty is made that the e-mail or attachment (s) are free from computer viruses or other defects.
