### ISSUE TITLE
Centrally updateable textbox

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#117]
**Is your feature request related to a problem? Please describe.**
Some monitoring is set up for some infrastructure which is used for one thing one week; then another thing the next week.  It would be nice to change the label easily centrally, so that the other dashboard viewers could see the new label more or less immediately, rather than after a reload.

**Describe the solution you'd like**
- a new element type - interactive label - editable text - something like that
- the text can be changed by any user in view mode which sends it to the backend
- the backend sends the text to the frontend

**Describe alternatives you've considered**
- user edits a "text" label and saves it & the other users reload

**Comment by ollytom** [comment]
Hmm. Can't really picture this. What I think we're talking about, currently, are static text elements which are manually updated week to week. Is that right?

**Comment by s2156945** [comment]
From a display point of view it would be the same as a statically defined text element.
But in view mode a user "Alice" could click on it, and update the text.
Other viewers "Bob" on other computers would get that text update after "Alice".
If meerkat restarted, the text would be kept.

**Comment by ollytom** [comment]
Ah ok I gotcha. It would be interesting to look into if and how Grafana handles this case;
if another client modifies a dashboard, whether other clients are notified of changes or reloaded or whatever.

**Comment by sol1-matt** [comment]
The ability for updates to a dashboard by user A to reload the currently loaded dashboard for user B has been implemented in #170
