### ISSUE TITLE
Changing element check type is counter-intuitive

### ISSUE THREAD

**Issue by jlownie** [meerkat-dashboard/meerkat#118]
**Describe the bug**
If you change the element type you also need to re-select the host.  The UI does not make this clear.

I have raised this as a bug rather than a feature usability issue is serious enough to warrant this.  The expected behaviour in this case is undocumented so it's unclear if it is working as designed.

**To Reproduce**
Starting with a host with multiple services defined in Icinga, a dashboard created and an element added to the dashboard:
1. Click on the Edit button for the element, which brings up the properties page for that element
2. Click "Hosts" under "Icinga Host and Service"
3. Click on the drop down box below and select a host
6. The text on the Element in the preview window (that displays how the dashboard will look) changes to "Up"
7. Click on the first drop down box underneath "Icinga Host and Service" and select "Icinga Host and Service" - nothing happens

**Expected behavior**
Either 
1. Meerkat should apply the newly selected element to the previously selected host, in which case the element's text should change to "OK" or whatever the correct value is for that host
2. Meerkat should clear the existing value in the host field so that you know that you need to re-select it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 105.0.5195

**Comment by davekempe** [comment]
Changing the element types causes the frontend to get into a pretty weird state. Perhaps the values need to be cleared when selecting the element type, so the user can just start again. Its not going to possible to really translate all the permutations from going from 1 element type to another, as they all have slightly different options. So perhaps we just need to wipe all the other settings when changing the element type and let the user start again.

**Comment by ollytom** [comment]
Trying to reproduce this one.

> 5. Click on the first drop down box underneath "Icinga Host and Service" and select "Icinga Host and Service" - nothing happens

Do you mean when changing the object type from, for example, "Host" to "Service Filter"?

**Comment by ollytom** [comment]
In grafana, a manual "run query" needs to be clicked.
On click, a little icon appears in the corner that is telling you that the element is being "refreshed".

In meerkat, the appearence of the element does change, but only on the next time the object state that it is referring to is updated. That happens automatically every 30ish seconds. If the state of the new object is the same, then the element will be displayed identically.

So I think I understand what you mean now jlownie :)
And I think what may help is a little icon like [refresh-cw][refresh] in the top corner of an element to show that it's doing something?

[refresh]: https://feathericons.com/?query=refresh

**Comment by ollytom** [comment]
The appearance of an icinga object element changes immediately after selecting the source icinga object(s) now.
When changing element type, form fields are reliably cleared.
