### ISSUE TITLE
FR: Refreshing image element type

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#119]
It would be great to be able to add elements of external images, and have them automatically refresh. This would let us embed graphs and pictures from other devices and systems to draw them alongside Meerkat dashboards.

You would be able to add a new element type of External Image, and enter the URL of the image. Also you would be able to specify the refresh rate of the image, and then the Meerkat front end would just refresh that image for the user each interval.

I don't believe that the Static Image element does this correctly, that is just for an uploaded image. This isn't really a Dynamic image. Of course it implies that the user's browser can reach the image as well, but that should be fine.

This would be good to embed grafana graphs, and images from devices like security cameras and video encoders.

**Comment by ollytom** [comment]
The thing I'm thinking about is where do we draw the line?
At what point does Meerkat change from "a dashboarding tool for Icinga" to a (poorly implemented) window manager? Window managers on all major OSs handle concurrency and state better than meerkat!

If we want to embed images, iframes(!!), or whatever else, what about opening another window?

**Comment by ollytom** [comment]
An argument against this type of feature, and almost any other element types, is that it pushes the program towards one that embeds arbitrary elements. But those types of systems already exist in the form of window managers in operating systems. And they are way better implemented. They aren't hamstrung by being run in a web browser either.

"Composition over inheritance"

Consider the case of embedding a grafana dashboard *within* meerkat. What about instead opening another window with grafana running next to it? No code needed.

**Comment by davekempe** [comment]
The thing is that meerkat intended deployment is for screens mounted on walls. There is limited real estate for these screens in NOC areas, and having embedded images alongside Icinga and other logical elements is perhaps unfortunately, the way to win the battle for NOC screen space. Meerkat while supporting links etc, is primarily meant for viewing and communicating essential information about infrastructure state etc. So having users have to click to open a graph is fine for some people, but some need the 'at a glance' state. 
A grafana graph, and a security camera feed alongside environmental state dashboard is a current customer requirement, and they would prefer not to have 2 different tools taking up valuable screen real estate. Does that mean Meerkat has to be a window manager? Perhaps. Are we doomed to repeat all the same mistakes as the past? Perhaps not. If someone pays, does it matter? Perhaps, but in this case, I'm sure the above reasons are solid enough.

**Comment by ollytom** [comment]
Oh oops haha just realised I replied to this twice!

**Comment by davekempe** [comment]
> Oh oops haha just realised I replied to this twice!

I just thought you were very passionate about it!

**Comment by davekempe** [comment]
I just tried playing gifs and jpegs using the HLS element type - videojs doesn't support these unfortunately, even though they are simpler!

**Comment by ollytom** [comment]
> I just thought you were very passionate about it!

Haha well you know, just all over the shop ;)

But seriously, there will be other ways of doing this without another feature in meerkat...
"A dashboarding tool for Icinga" is a fantastic focus that most software projects would kill to have.

> If someone pays, does it matter?

Depends on who you ask! If the relationship is "write request, wait, $$$" then no, it doesn't matter.
But if the relationship is in the code, then maybe it does!

**Comment by ollytom** [comment]
> I just tried playing gifs and jpegs using the HLS element type - videojs doesn't support these unfortunately, even though they are simpler!

Ah yeah I know! I've been thinking of if there's a way to remove that HLS element, too haha ;)
Ideally it would be a plain `<video>` tag, but not possible :(

**Comment by ollytom** [comment]
> The HLS element is in use and appreciated by many people. We did try with a video tag initially. The technology is 
> messy under the hood.

Yeah I get that. The only browser which supports HLS natively is Safari!

Anyway, I just came up with a "dumb" way of implementing this feature which might get us 80% of the way there with only a tiny bit of code.
For my future self/anyone else who wants to have a go.

New frontend/src/elements/img.jsx

	import { h, Fragment } from "preact";
	
	export function ImgOptions({ options, updateOptions }) {
		return (
			<fieldset>
				<label for="src">Source</label>
				<input
					class="form-control"
					id="src"
					placeholder="https://sol1.com.au/wp-content/themes/sol1/favicon-196x196.png"
					value={options.imgSource}
					onInput={(e) => updateOptions({ imgSource: e.currentTarget.value })}
				></input>
			</fieldset>
		);
	}

In frontend/src/editor.jsx:/ElementSettings/

	if (selectedElement.type === "audio-stream") {
		ElementOptions = (
			<ImgOptions
				updateOptions={updateElementOptions}
				options={selectedElement.options}
			/>
		);
	}

And frontend/src/editor.jsx:/DashboardElements/

	if (element.type === "Image") {
		ele = <img src={element.options.imgSource}></img>;
	}

**Comment by ilie01** [comment]
As Dave mentioned earlier, I'm also planning on implementing Meerkat over some TV screens where user input is not an option. At this point i need to insert the list of active critical alarms per hostgroups (as iframes) or some other object. 
Icinga2 already has this info but i don't see the option of inserting this into my meerkat dash (something like the image attached) 
![image](https://user-images.githubusercontent.com/116039718/196294750-bff4c57c-dcc6-4c93-b61c-d11afe47c923.png)
