### ISSUE TITLE
Admin creds a compulsory - view is only option for new dashboards

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#120]
**Describe the bug**
When you start the current master branch version without defining admin username and password, any dashboard can't be edited. If you go back and define them in the config file and restart, the edit/clone/delete options appear.

**To Reproduce**
1. start meerkat with admin creds commented out.

```
#AdminUsername = "admin" 
#AdminPassword = "password"
```

2. Create new dashboard, saves ok, but then on main screen edit/clone/delete are missing
3. to get the buttons back, you can configure Admin creds in toml file and restart meerkat

**Expected behavior**
Admin feature should be optional. If its set, the buttons get hidded until you basic auth. If its unset, you can do whatever you want.

**Comment by ollytom** [comment]
Bug will be around how the frontend determines whether authentication is configured or not.
see `authConfigured()` in frontend/src/meerkat.js

**Comment by ollytom** [comment]
Ok got this working. I was just being a noob with handling state between components; needed to read react JS documentation on state hooks. Doing some final testing then will send patch!

**Comment by davekempe** [comment]
we have a different problem now - setting admin creds makes the buttons disappear. at least its not a catch22 anymore.
Ill add more detail shortly.

**Comment by ollytom** [comment]
Meerkat authentication can be handled entirely by an authenticating proxy in front of meerkat. This will be documented with https://github.com/meerkat-dashboard/meerkat/issues/135.
