### ISSUE TITLE
Static text alignment used?

### ISSUE THREAD

**Issue by ollytom** [meerkat-dashboard/meerkat#123]
The Static Text element provides text alignment options (left, center, right; top, middle, bottom).
I'm struggling to think of a use case where you would want text aligned to the bottom right corner, which couldn't also be served by just moving the element.
Is this feature really relied on by anyone?

**Comment by davekempe** [comment]
For multi-line text right alignment looks neater and is easier to line up for example. I used this the other day in a dashboard I made, and it had a few bugs, which I haven't figured out, but are probably related to #115. If moving the elements and resizing them wasn't so buggy, yes, we could probably remove the vertical alignment.  The left/right/center however is useful for multi line boxes. Its an ease of use feature I guess.

**Comment by ollytom** [comment]
> For multi-line text right alignment looks neater and is easier to line up for example. I used this the other day in a dashboard I made, and it had a few bugs, which I haven't figured out, but are probably related to #115. If moving the elements and resizing them wasn't so buggy, yes, we could probably remove the vertical alignment.

Ironically the source of those bugs is in part due to the presence of the features and how they interact.
It’s fiddly to get consistent behaviour!

What I had in mind here was looking for opportunities to pare down (or remove) some of those features in an effort to resolve some of those bugs. But sounds like this feature is useful so I can probably just close this off. Thanks for the input!
