### ISSUE TITLE
URL format change will break existing user links to dashboards

### ISSUE THREAD

**Issue by sol1-matt** [meerkat-dashboard/meerkat#129]
**Is your feature request related to a problem? Please describe.**
Dashboards have links to other existing dashboards. Existing dashboard links are saved in browser favorites. External applications reference existing dashboards. There are many links to existing dashboards and they are primary user driven. 

The url path in the latest meerkat has changed from `domain/action/dashboard` to `domain/dashboard/action`. 

This change will break all the existing links.

**Describe the solution you'd like**
Permanent redirect on all old paths, `domain/action/dashboard`, to the new paths, `domain/dashboard/action`.  

**Describe alternatives you've considered**
Not changing the paths used.

**Additional context**
The old actions are `view` and `edit`. If we have a permanent redirect on these actions that means dashboards won't be able to be named view or edit. It might be a good idea to have a `protected_names` array which contains a series of protected strings that can't be used in dashboard name. Besides `view` and `edit` other protected names would be things like admin, user, groups, settings, etc.... These are values that could be used in the future for meerkat functionality so blocking their use now prevents future problems. It also wouldn't be burdensome to not allow dashboards to use these names as they are rubbish names for dashboards.

**Comment by ollytom** [comment]
Resolved in 9d3e3cc5897f646
