### ISSUE TITLE
Background upload fails silently

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#130]
**Describe the bug**
When uploading the background fails (e.g. permission denied, 413 Too Large), meerkat doesn't alert the user

**To Reproduce**
1. Go to edit a dashboard
2. Click on browse
3. Find a PNG which is too big for the  nginx config (e.g. 2MB)
4. Nothing happens, same background is kept.
5. If you look in browser dev tools you see the 413 Too Large or 403 Permission denied or whatever

**Expected behavior**
Errors are passed through to the user, e.g. a popup with the result HTML maybe

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux (Pop!OS)
 - Browser: Fifrefox
 - Version 102.0 (64 bit)

**Workaround**
Upload a smaller background

**Comment by ollytom** [comment]
Oops didn't mean to close this one. We want to catch other errors at the HTTP response level. 

In particular, `meerkat.uploadFile()` needs to inspect the HTTP status code so we catch errors sent by any middleware or reverse proxies (e.g. as @s2156945 mentioned a HTTP too large status from nginx).

**Comment by ollytom** [comment]
I found a patch for this - and on background uploading/storage in general - on another computer that I've been working on.
I'll tidy it up and upload it!
