### ISSUE TITLE
Icinga Services with a slash in the name don't get results / can't get plugin data or extract text from the check result

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#131]
**Describe the bug**
Due to the url handling in the meerkat go backend, a 'not fully escaped' URL is passed to icinga, e.g.

meerkat_1   | 2022-12-23T01:23:28.113649802Z 2022/12/23 01:23:28 /root/backend/icinga.go:192: Proxying to icinga: GET https://icinga.in.broadcastservices.cloud:5665/v1/objects/services/tbsp-xos-ou01-a%21VOS360%20Service%20End%20to%20End%20United%20Cup%20WF/brightcove?attrs=last_check_result

which gets empty results

**To Reproduce**
1. Create an Icinga check with a '/' in the name
2. Start to add it to meerkat as an "icinga card" as normal
3. Scroll down in the pane to "Plugin data mode"
4. See that it is unavailable

**Expected behavior**
1. Services with '/' (or other icinga-legal characters) in the name behave as normal
2. Unexpected empty results are logged or flagged in the GUI

**Workaround**
Change the name of the Service to not have a slash in it, I suggest tilde (~) instead

**Comment by ollytom** [comment]
Haha lol. The handling of the Icinga API by the backend is really brittle.
Manually putting strings together to make a HTTP request all over the place as soon as meerkat receives a request.

There's 2 issues:

1. The backend is not returning the error it receives from the API to the client; it just assumes there is JSON there to decode, then re-encode to return to the client. No HTTP status checking.
2. The client (javascript) is not correctly URL-encoding the icinga object name.

There's basically zero code reuse so refactoring can take a long time and is prone to errors (I've made mistakes already).
Instead I'm reducing the number endpoints the frontend can hit (see for example https://github.com/meerkat-dashboard/meerkat/issues/132 and https://github.com/meerkat-dashboard/meerkat/issues/133)

**Comment by ollytom** [comment]
No longer an issue as names, attributes etc. are not shuffled between query parameters, JSON bodies and URL paths as raw strings any more (yes all 3 were used!)
