### ISSUE TITLE
Rendering more attributes in icinga object cards

### ISSUE THREAD

**Issue by ollytom** [meerkat-dashboard/meerkat#132]
In Meerkat versions < 2.1.x, "Dynamic text" elements render attributes of Icinga objects like custom variables and performance data.

Currently icinga object elements also render attributes of the objects they represent.
But it's hardcoded to render a textual representation of the object state (e.g. up, down, ok, critical...).

Previously this feature worked by having two different API endpoints, with two different caches, with two different data models.
There were lots of bugs; there was a lot of code just gluing things together which allowed no time or headspace for basic error handling.

We can add a feature to object elements that allows selecting which attributes to render as the card text.

Given an icinga object, such as:

```
{
    "attrs": {
        "__name": "example.com!test",
        "acknowledgement": 0,
        "acknowledgement_expiry": 0,
        "acknowledgement_last_change": 0,
        "action_url": "",
        "active": true,
        "check_attempt": 1,
        "check_command": "check-mdadm-by-ssh",
        "check_interval": 180,
        "check_period": "",
        "check_timeout": null,
        "command_endpoint": "",
        "display_name": "check mdadm - example.com",
        "downtime_depth": 0,
        "enable_active_checks": true,
        "enable_event_handler": true,
        "enable_flapping": false,
        "enable_notifications": true,
        "enable_passive_checks": true,
        "enable_perfdata": true,
        "event_command": "",
        "executions": null,
        "flapping": false,
        "flapping_current": 0,
        "flapping_ignore_states": null,
        "flapping_last_change": 1646470012.694884,
        "flapping_threshold": 0,
        "flapping_threshold_high": 30,
        "flapping_threshold_low": 25,
        "force_next_check": false,
        "force_next_notification": false,
        "groups": [],
        "ha_mode": 0,
        "handled": false,
        "host_name": "example.com",
        "icon_image": "",
        "icon_image_alt": "",
        "last_check": 1676869733.845887,
        "last_check_result": {
            "active": true,
            "check_source": "icinga.example.com",
            "command": [
                "/usr/lib/nagios/plugins/check_by_ssh",
                "-C",
                "'/usr/bin/sudo' '/usr/lib/nagios/plugins/check_md_raid'",
                "-H",
                "58.96.22.133",
                "-i",
                "/var/lib/nagios/.ssh/id_rsa",
                "-l",
                "nagioschecker",
                "-o",
                "StrictHostKeyChecking=no",
                "-t",
                "60"
            ],
            "execution_end": 1676869733.845816,
            "execution_start": 1676869733.541765,
            "exit_status": 0,
            "output": "OK - Checked 1 arrays.",
            "performance_data": [],
            "previous_hard_state": 0,
            "schedule_end": 1676869733.845887,
            "schedule_start": 1676869733.54,
            "scheduling_source": "icinga.example.com",
            "state": 0,
            "ttl": 0,
            "type": "CheckResult",
            "vars_after": {
                "attempt": 1,
                "reachable": true,
                "state": 0,
                "state_type": 1
            },
            "vars_before": {
                "attempt": 1,
                "reachable": true,
                "state": 0,
                "state_type": 1
            }
        }
    },
    "joins": {},
    "meta": {},
    "name": "example.com!test",
    "type": "Service"
}
```

We'd iterate through the object's keys and generate options from there.

To get at nested keys, we'd need to specify a string representation to
get at object properties. Javascript uses `.`. That should be safe in
javascript and there is lots of open source code to work from.

The previous handling of this in previous meerkat versions is poor.
The code was difficult to read as it was tightly coupled with all the (p)react component stuff.
It turned out to be a waste as the logic wasn't portable between other icinga (or javascript) projects.

The HTML we want would probably be:

```
<select>
    <option value="state">state</option>
    <option value="next_check">next_check</option>
    <option value="check_interval">check_interval</option>
    ...
</select>
```

**Comment by s2156945** [comment]
Perfdata + Filter behaviour:
V2 Current - in the json is saved an "id" (now "objectName") which is used for text extraction and "filter" for the status/colour. I think this is an accidental feature but we've used it a lot;  The edit gui doesn't really support it.

Possible Solutions for V3:
- same as V2 - specify the object for the text extraction separately from the filter for the status
- aggregates - for perfdata sum/average/min/max the selected perfdata item for display
- concatenate - perfdata - output one number for each matching filter item
- concatenate - output - join the check output lines together before running the regex extraction per #153

Some of these it would be useful to be able to set the object order in the filter, e.g. alphabetical by host/service or numerical by perfdata/id something

**Comment by ollytom** [comment]
I've got the logic done for accessing the attributes of an object via a select expression.
For example, accessing the output of the last check result is done with "attrs.last_check_result.output".
Just need to write some tests and a bit more inline documentation.
It's a little bit fiddly; it makes use of recursion and there's some javascript-isms.
