### ISSUE TITLE
Stuck on react-widgets v4.4.4

### ISSUE THREAD

**Issue by ollytom** [meerkat-dashboard/meerkat#134]
react-widgets is used for a single UI element: the "Combobox". It's a fancy <select> element that provides autocompletion. We're stuck on version 4.4.4 - published over 4 years ago.

react-widgets is not high quality code. It pulls in many dependencies (see the [dependency graph](https://npmgraph.js.org/?q=react-widgets%404.4.4)) and it requires its own CSS (see ui/react-widgets.css).

We could upgrade it.
But I don't think the maintenance burden is worth the different - maybe better, maybe worse - behaviour in the UI.
The maintenence burden is demonstrably too high: outdated dependencies are partly to blame for this project's stalled development up until recently-ish!!

[npmgraph]: https://npmgraph.js.org/?q=react-widgets%404.4.4

**Comment by davekempe** [comment]
Being able to search elements when selecting them is an important feature. Large lists of services are hard to work with. Not sure what the right react element is, but I recall this element was implemented to do a search and refinement feature.

**Comment by ollytom** [comment]
Replaced ComboBox with a boring `<select>` element.
Now that react-widgets is gone we can optimise. Tracking in https://github.com/meerkat-dashboard/meerkat/issues/137
