### ISSUE TITLE
CheckLine Elements are transparent

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#139]
**Describe the bug**
CheckLine Elements ported from old meerkat are not visible. They appear in the edit list and have location and size in edit, but do not have a strokeColor.  If you edit the DOM and add a strokeColor they appear.

**To Reproduce**
1. port a dashboard with checkLine elements from old meerkat
2. Open the dashboard in view mode

**Expected behavior**
checkLine elements should appear in the same color as the equivalent checkSVG element
- Green when everything is OK
- orange for warning
- red for critical
- purple for unknown
- variants for acknowledged
- missing/transparent when the configured check is not available in icinga

**Screenshots**
Previos working dashboard: 
![image](https://user-images.githubusercontent.com/21114973/220028296-ab0cbe1c-d673-4afb-a8a2-b9cb8069f6a1.png)
New dashboard with invisible checkLine elements:
![image](https://user-images.githubusercontent.com/21114973/220028568-2a2c319c-b71e-4629-8052-b5e1b4e66edc.png)

**Additional context**
Appears that line.jsx has not been updated at all in the way that svg.jsx has

**Comment by ollytom** [comment]
> Appears that line.jsx has not been updated at all in the way that svg.jsx has

Yes it is exactly that - I ran out of time :( Thanks for writing this!!
