### ISSUE TITLE
Data extraction in Icinga Card not implemented

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#141]
**Describe the bug**
In Meerkat 2 it was possible to extract/display data from the icinga check in two ways:
# choose some perfdata to display from a dropdown
# select some output from the icinga check output using a regex

This is no longer possible to configure

For dashboards ported from meerkat 2 the card simply shows the status (critical) rather than the extracted data

See screenshots in #139

**Comment by ollytom** [comment]
Duplicate of #132
