### ISSUE TITLE
Icinaga Line elements always yellow

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#146]
**Describe the bug**
In V3 the icinga lines are always yellow, when looking at real icinga data

**Observed Behaviour**
![image](https://user-images.githubusercontent.com/21114973/222349278-4bc66a23-ee81-4c12-ada9-b19e07ed8015.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/21114973/222349342-75709de3-fc98-4b69-a7ca-dc24d74dd94a.png)

**Additional context**
They do work on https://demo.meerkat.run/issue-139/view

**Comment by ollytom** [comment]
Yes this is a funny one! I haven’t been able to replicate it. Tried on a few different operating systems, and with the same dashboard.

Can you paste output of meerkat -v (or click "About" in UI)?

Next, can you confirm frontend stuff is rebuilt - `cd ui && npm run build` and see if same behaviour?

Finally can you send logs? meerkat writes to standard output. for browser logs, if running firefox, open web dev console (Tools -> Browser Tools -> Web Developer Tools). in the window that opens, click the tab "Console". open the dashboard and let it run for a bit. finally right click on the output and select "Save all messages to a file"

Thanks! :)

**Comment by s2156945** [comment]
`cd ui && npm run build` I think fixed it; but I think the geometry is off #150
