### ISSUE TITLE
Autoplaying video

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#147]
**Describe the bug**
In V3 the video elements do not behave the same as in V2

**Expected behavior**
These should be the default, or at least possible options
- fill the "box"
- autoplay
- sound is off by default

**Additional context**
If this is something which can be addressed in "porting" V2 dashboards to V3, i.e. these behaviours can be not default; e.g. different types:
- video - does not start automatically but when you do start it has sound
- video muted - as above but you need to turn on the sound if you want it
- video autoplay muted - current V2 behaviour
- video autoplay with sound - video autoplays with sound

**Comment by ollytom** [comment]
I think this may be a quick change by setting autoplay in the HTML video element here

https://github.com/meerkat-dashboard/meerkat/blob/8ff1dbeb5e8c2201189aa38357c125c73f7522e2/ui/src/elements/video.jsx#L43

Ref https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
and https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
