### ISSUE TITLE
Icinga lines do not have the same geometry

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#150]
**Describe the bug**
Using a V2 json "ported" to V3, the arrows are different lengths (major) and have different shaped heads (minor)

**Expected behavior**
It is possible to port V2 json dashboards in a way that results in the arrows being in the same place

**Screenshots**
![image](https://user-images.githubusercontent.com/21114973/222355879-a8223f0d-0707-4fdd-a640-2823219f2ef8.png)

![image](https://user-images.githubusercontent.com/21114973/222355137-c1d8d1d4-d120-46ee-8b04-0ba1bdb088d9.png)

**Comment by ollytom** [comment]
Maybe related to #151? The SVG may have some padding/margin that wasn’t before.

**Comment by s2156945** [comment]
Different in view and edit modes
![image](https://user-images.githubusercontent.com/21114973/223011637-2c98b743-56ac-46ed-be48-2629652eaabd.png)
![image](https://user-images.githubusercontent.com/21114973/223011672-4951899b-1628-4e4e-badf-3a80ef9f2034.png)

**Comment by s2156945** [comment]
![image](https://user-images.githubusercontent.com/21114973/223011791-b86d4b2f-d865-4b9c-a39f-6b0a6bb6735a.png)
Geometry changed since 58a7946

**Comment by s2156945** [comment]
Zooming in affects the lines
![image](https://user-images.githubusercontent.com/21114973/223011981-d6b01b73-c480-4ce8-9ae7-bde0e5099ccd.png)
