### ISSUE TITLE
No element rendered if no matching icinga object

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#152]
**Describe the bug**
Useful

![image](https://user-images.githubusercontent.com/21114973/223013249-d914fbbf-8dd6-47c8-afca-952f5d96c8c8.png)

**Comment by ollytom** [comment]
To reproduce, can create an element by editing the dashboard file and adding a "bad" element like:

	    {
	      "type": "check-card",
	      "title": "nonexistent",
	      "rect": {
	        "x": 6.162464985994398,
	        "y": 27.491785323110623,
	        "w": 26.945525291828794,
	        "h": 19.82475355969332
	      },
	      "options": {
	        "objectName": "I do not exist",
	        "objectType": "service"
	      },
	      "rotation": 0
	    }

From there, fiddle with ui/src/elements/i2object.jsx

**Comment by ollytom** [comment]
@s2156945 Does this look ok? See https://demo.meerkat.run/issue-152/info

**Comment by s2156945** [comment]
Looks are OK; the '~' was displayed on the existing dashboards as a "fallback" for the regex not matching.  I guess it makes sense as a default, but the V2 default was empty string, so I lean towards that.

**Comment by ollytom** [comment]
Yes actually empty string feels clearer too in this particular case.
`~` makes you wonder if it means anything. OK I'll commit with empty string. Thanks :) !
