### ISSUE TITLE
Authenticated HLS streams

### ISSUE THREAD

**Issue by ollytom** [meerkat-dashboard/meerkat#158]
Currently the video player is just a plain video HTML element:

	<video src="https://akamai.example.com/HLS/example.m3u8" />

But some services require authentication to access the stream.
For example, some akamai streams require supplying a unique token.

Akamai recommend having the client request a token and then supply it with all subsequent requests

Alternatively a static token with a long expiry - e.g. 1 year - may be appended to the URL as a query parameter. The `<video>` element above would be:

	<video src="https://akamai.example.com/HLS/example.m3u8?hdnts=exp=170..." />

Smarter clients do not have to worry about expiring tokens since they are generated as required.
A dumber client requires no code; it's still just a URL.
But how do we track token expiration?
We'd likely forget, and a year later we'd be surprised when we can't read streams any more.

## Suggestion

Tokens appended to Akamaized URLs contain an expiry timestamp.
An independent process could scan for URLs, read the token, and calculate if it is expiring "soon".

Here's an awk program which does that:

	# Reads Akamai stream URLs from the standard input then prints the
	# duration of time until the appended token, if any, expires.
	BEGIN {
		FS = "?"
	}
	{
		base = $1 # http:/example.com/channel/test/video.m3u8
		query = $2 # hdnts=...
	
		# Find the "exp" parameter holding a Unix timestamp for the
		# expiry time.
		pos = match(query, "exp=[0-9]+")
		if (pos == 0) {
			print "no expiry parameter"
			next
		}
	
		# extract the timestamp
		param = substr(query, pos, RLENGTH)
		n = split(param, elements, "=")
		if (n <= 1) {
			print "missing epoch time"
			next
		}
		expiry = elements[2]
	
		"date +%s" | getline now
		until = expiry - now
		printf "token for %s expires in %.1f days\n", base, until/86400
	}

We could find all akamai URLs used in dashboards and pipe them in:

	grep akamaized.net dashboards/*.json | akamaiexpire

	token for https://akamai.example.com/channel/1/master.m3u8 expires in 317.9 days
	token for https://akamai.example.com/channel/6/master.m3u8 expires in 288.1 days

## Summary 

It is easier to test, maintain and (most importantly!) understand this small program
than a more complicated javascript player in Meerkat.

The logic in the little program has general applicability outside of meerkat too.
Obviously awk isn't the only way to do this. I've just used it to illustrate that nothing fancy is required.

## My 2c

I favour token management outside of meerkat. Meerkat is intended to provide a high-level monitoring overview.
Video elements provide an at-a-glance *output* of some HLS stream.
CDN-specific authentication flow is a server-side implementation detail that neither Meerkat nor the browser need to care about.

**Comment by sol1-matt** [comment]
Icinga monitoring would be better suited to alerting to token expiry, that is what it is designed to do.

**Comment by sol1-matt** [comment]
I possible meerkat function would be to allow api update of meerkat dashboards so the cycling of tokens could be automated externally.
