### ISSUE TITLE
Line and arrowhead coloured inconsistently

### ISSUE THREAD

**Issue by ollytom** [meerkat-dashboard/meerkat#159]
Sometimes the arrowheads of lines have a different fill colour to the line itself.
The line may be orange but arrowheads are purple.

## Recreation

Create a dashboard consisting of a few lines.
The elements must reference a real object with a state that is not unknown.

After the dashboard is completely rendered, resizing the browser window, even just by a single pixel, results in the arrows being coloured consistently!

**Comment by sol1-matt** [comment]
this problem appears to be from creating multiple markers with the same id then referencing the markers for each arrow head for each line with the common id.

aka they picked up the wrong arrow head.

There were also further problems with arrow layout and alignment as the layout of these arrow div -> svg -> line is quite different to the old layout div -> svg -> line -> poly -> poly.
