### ISSUE TITLE
Icinga Card is missing Status text

### ISSUE THREAD

**Issue by sol1-matt** [meerkat-dashboard/meerkat#185]
**Describe the bug**
Icinga Card objects should return the text of the status if attributes or no match return nothing.
This is not happening, the card is blank.

**To Reproduce**
1. Add Icinga Card with a attribute from the performance data that is not valid and save
Card has no output text, only state.

**Expected behavior**
Returns the same set of values as single hosts/services

**Screenshots**
Top is correct output, bottom is incorrect output because the perfdata selected doesn't exist
![image](https://github.com/meerkat-dashboard/meerkat/assets/17868735/d0c4a39a-7c73-4b06-816f-f8595b423519)

**Additional context**

**Comment by 63** [comment]
fixed in 57cd5e3fda4033a77908a7e6ddd4586a25bf88ab
