### ISSUE TITLE
Discussion: Meerkat frontends should move from using icinga data to holding their own element objects which the Meerkat server generates from Icinga data or other sources

### ISSUE THREAD

**Issue by sol1-matt** [meerkat-dashboard/meerkat#188]
If the Meerkat server maintained a cache of element data that updated and pushed to dashboards then...

- Dashboards become much more simple, they hand display only
- No need to make API call's on `StateChange` as the event streams contains State that can be extracted and used to update the cache. 
- No need to make API calls on many/all? `CheckResult` event streams as those events contain perfdata and output
- Frontend only contains element data which is the minimum data it needs to display, so it is as secure as possible.
- Makes it easier to add other backends besides Icinga as the frontend dashboards will need little to no changes (the elements can be reused).

**Comment by s2156945** [comment]
If Meerkat server remains just being a proxy:
* Backend remains simple
* Data changes/enhancements generally don't affect the backend
* Can add other backends beside Icinga by using similar elements which perhaps inherit from a common parent class (e.g. "nagios-card" and "icinga-card" both inherit from "card")

**Comment by davekempe** [comment]
We have moved on this already and the new Event stream feature makes this discussion redundant.

**Comment by davekempe** [comment]
closing for now
