### ISSUE TITLE
The UI to change a dashboards 'folder' doesn't work. 

### ISSUE THREAD

**Issue by sol1-matt** [meerkat-dashboard/meerkat#208]
**Describe the bug**
Users can't change the 'folder' of a dashboard from the settings page.

**To Reproduce**
1. Go to dashboard settings
2. Change Folder value
3. Save

The dashboard folder value reverts to the original value.

**Expected behavior**
The dashboard should save the new value

**Additional Info**
It is possible to change the folder by editing the dashboard json manually.

**Comment by sol1-matt** [comment]
It would be nice if the folder field auto suggest existing folder names at the same time, this would be a enhancement though so fixing the bug without this enhancement is the only critical part.

**Comment by 63** [comment]
2211036ebfb63e1abd76d16424fd90522848714a
