### ISSUE TITLE
Don't submit filter search results on every keystroke

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#22]
In GitLab by @matthew.palmer on Oct 10, 2020, 13:30

When editing an element which uses a host or service filter to select which object('s|s') status to use, the `<input>` element for the filter currently uses an `onChange` handler to update the filter parameter.  This has the unpleasant side-effect of updating the element's display in the preview pane on every keystroke, so as you're typing in a filter specification, the element "flickers" as the filter spec currently in the box changes between valid and invalid.  This is ugly.  Need to figure out which event handler is more appropriate than `onChange`, so that the filter only actually updates when the `<input>` loses focus, or perhaps when Enter is pressed, or... something.

**Comment by ollytom** [comment]
The debounce has been implemented a while ago.
