### ISSUE TITLE
Host based elements are displaying the check result rather than the host state.

### ISSUE THREAD

**Issue by sol1-matt** [meerkat-dashboard/meerkat#220]
**Describe the bug**
Host based elements are displaying the check result rather than the host state.
The check result is from `results[0].attr.last_check_result.state` and is the result the check returns. This can be `OK`, `WARNING`, `CRITICAL`, `UNKNOWN` or `PENDING`.

A hosts status is from `results[0].attr.state` and is `OK`, `CRITICAL`, `UNKNOWN` or `PENDING`.

**To Reproduce**
1. Create test dashboard
2. Add element with Element Type of Host
3. Select a host from the drop down that is in a OK state but the check is returning a warning state, eg: host with http check returning 404.
The element returns as warning which is incorrect.

**Expected behavior**
The element state should match Icinga's state

**Additional context**
Meerkat can predict what the host state should be based on the `last_check_result.state` value if the event stream doesn't have the hosts state and only has the last check results state.

 - Meerkat Version = 3.1.0

**Comment by 63** [comment]
https://icinga.com/docs/icinga-2/latest/doc/03-monitoring-basics/ 
![image](https://github.com/meerkat-dashboard/meerkat/assets/55000067/8e555cf8-3afb-4ed7-bc69-84e5281831f8)
