### ISSUE TITLE
Editing Window Displays Incorrect Information when Switching Between Elements

### ISSUE THREAD

**Issue by thi-doan** [meerkat-dashboard/meerkat#232]
**Describe the bug**
When initially clicking on an element to edit, the edit window on the left opens and correctly displays the information for the selected element. However, if the edit window is still open and another element is clicked for editing, the Name of the most recent element is displayed in the edit window, but all other fields still reflect the information from the first opened element.

**To Reproduce**
1. Open a dashboard in edit modus. 
2. Click to edit an element
3. Click to edit another element

**Expected behavior**
The edit window should display the correct information for the most recently clicked element, including all fields such as Icinga Host and Linking Url, without retaining information from the previously opened element.

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chrome
 - Version 1.1.12

**Comment by davekempe** [comment]
Thanks, this is a frontend javascript bug. @63 should be able to take a look next week or so.
I guess the workaround for now is to save the element, and then go back to the list and pick a new element to edit.

**Comment by thi-doan** [comment]
Hey, do you have any updates for us on this? :)

**Comment by 63** [comment]
Could not reproduce
