### ISSUE TITLE
Provide help for Icinga filter syntax

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#24]
In GitLab by @matthew.palmer on Oct 10, 2020, 13:34

Some sort of little icon next to the filter `<input>` element which, when clicked, provided a pop-up with our best guess of what Icinga API filter syntax actually was, would be very handy.  It's a weird sort of language, and bears absolutely zero resemblance to what people who've only dealt with the Icinga web API before would expect.

**Comment by ollytom** [comment]
> It's a weird sort of language

A weird obscure language with strange, unusual logical operators like `&&` meaning "and"; `||` meaning "or".
A language with syntax based heavily upon, if not identical to, an obscure family of languages, originating over 50 years ago, starting with a relatively obscure language called "C" ;)

But yeah haha totally agree that it's unclear. At the very least a link to the documentation would be a big step forward.
The official documentation isn't great (I have 0 grasp on what is actually available, and the docs are unclear). But it's better than nothing at least! The best link would probably be https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#filters

Our form could look something like:

	<fieldset>
		<label class="form-label" for="filter-expression">
			Filter expression
		</label>
		<input
			class="form-control"
			id="filter-expression"
			name="filterExpr"
			type="text"
			placeholder="service.name == test"
			value={value}
			onInput={onInput}
		></input>
		<small class="form-text">See the
			<a href="https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#filters>
				Icinga documentation
			</a> for a guide on writing filter expressions.
		</small>
	</fieldset>

**Comment by ollytom** [comment]
Icinga filter expressions are not exposed in the interface any more
