### ISSUE TITLE
Consider embedding the background image in the dashboard JSON

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#25]
In GitLab by @matthew.palmer on Oct 19, 2020, 10:44

This may seem, on the face of it, to be a deranged thing to do, but hear me out.

At the moment, a dashboard consists of two "main" data items: (1) the JSON description of the elements (what they are, where they live, their parameters, etc), and (2) the background image.  They are stored separately on disk (in entirely separate directories, even), and are not related to each other except by a reference in the dashboard JSON to the (content-encoded) filename of the image.

For various reasons, this offends my aesthetic sensibilities.

Firstly, if you delete a dashboard JSON file, the background image isn't necessarily deleted, and once the dashboard JSON is gone, there's no way to ever know what its background image was (so cleaning it up later is a matter of enumerating all the *other* dashboards, listing their background images, and then deleting the image file(s) that aren't listed -- eeeeugh!).  A similar problem ("orphaned" dashboard backgrounds) can happen if you create a new dashboard, upload a background image, and then don't save the dashboard.

Secondly, when you want to retrieve a dashboard, you need to make two requests: first, one for the JSON dashboard description, and then a second for the background image.  These can't be made in parallel, because you need to read and parse the dashboard description to find out what image filename you need.

Finally, and the thing which made me think this might be entirely an unhinged idea, is that Narwhal will be incorporating Meerkat dashboards, and the most likely approach to do that will be to request the dashboard JSON directly from Meerkat, and render it within Narwhal.  This is a neat idea, but that'll likely require Narwhal proxying Meerkat requests from the user, and it'll simplify the proxy implementation if there's fewer requests that need to be proxied.

So, my recommendation is for dashboard background images to be base64-encoded, jammed into the dashboard JSON, and uploaded as a single unit to Meerkat.

Here endeth the sermon.

**Comment by ollytom** [comment]
> Firstly, if you delete a dashboard JSON file, the background image
> isn't necessarily deleted,

Right - as other dashboards may reference that image file.

> and once the dashboard JSON is gone, there's no way to ever know what
> its background image was (so cleaning it up later is a matter of
> enumerating all the other dashboards, listing their background images,
> and then deleting the image file(s) that aren't listed -- eeeeugh!).

But is this such a big deal? A script could be run in a cron job,
say once per week,
which deletes orphaned image files.

> Secondly, when you want to retrieve a dashboard, you need to make two
> requests: first, one for the JSON dashboard description, and then a
> second for the background image. These can't be made in parallel,
> because you need to read and parse the dashboard description to find
> out what image filename you need.

For a relatively infrequent operation, making two HTTP requests to a
server that is likely to only go through the local network (Meerkat is
likely installed in a controlled network not accesible from the
internet) is probably no big deal (relative to all other network
requests going on).

What we lose by base64-encoding is usability. We lose meaningful
people-friendly names for the sake of making it easier for the
computer.

If we are really concerned about two requests, we could ensure HTTP/2
support.

If we are really concerned about performance, we could look at
implementing the GUI as a WASM application using WebGL or WebGPU or
so. We could also look at changing the GUI behaviour of polling the
backend to receiving updates over a WebSocket.

I'll create an issue for writing a little clean up script to remove
orphaned background images. This would be cool for someone new to the
Meerkat project to do!
