### ISSUE TITLE
Add meerkat variables functionality to linkURL field and others

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#53]
In GitLab by @max1 on Jul 28, 2021, 17:00

We need to add the existing variable functionality to different fields in meerkat the "linkURL" field (the field for controlling which link you can navigate to when you click on a card) and "text" field (this is the text that displays on a static card).

Variables need to work with
- [ ] type: static-text, field: text
- [ ] objecttype: service, host, field: filter
- [ ] objecttype: service, host, field: linkURL

**Comment by ollytom** [comment]
Templating/variables/tags (which is which?!) have been removed.
