### ISSUE TITLE
Increase limit of allowed variables in the templates feature

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#54]
In GitLab by @max1 on Jul 28, 2021, 17:06

We need to increase the maximum allowed amount of variables allowed in meerkat. This will need to be a limit of 50 and then add overflow-y and max-height on the modal so a scroll bar will appear allowing more variables to be set in the modal.

**Comment by ollytom** [comment]
This is completed; there's a limit of 50. Seems bloody high to me but anyway!
