### ISSUE TITLE
Display version on editor and viewer

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#60]
In GitLab by @ken on Oct 1, 2021, 13:57

## Info

To assist debugging, display meerkat version on web interface

**Comment by afoster** [comment]
![Screen_Shot_2021-10-01_at_6 05 58_pm](https://user-images.githubusercontent.com/20520/176088939-433a35a3-4334-4533-aa1e-2f331f4af122.png)

**Comment by ollytom** [comment]
When we build a go program, the linker embeds VCS and go module information in the binary.
We can get that at runtime using the runtime/debug package.
https://godocs.io/runtime/debug#BuildInfo
Here's a http.HandlerFunc which writes that build info as a JSON-encoded response:

	func buildInfo(w http.ResponseWriter, req *http.Request) {
		info, ok := debug.ReadBuildInfo()
		if !ok {
			// HTTP 204 no content?
		}
		json.NewEncoder(w).Encode(info)
	}

In the frontend, to fetch the version from the buildinfo:

	async function version() {
		const res = await fetch("/buildinfo")
		let info = res.json()
		return info.Main.Version
	}

How and where to render that version string? That's way out of my league... 🆘🙏
