### ISSUE TITLE
Meerkat Checks on Icinga Services which are removed and replaced remain in state 'Unknown'

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#61]
In GitLab by @woody on Dec 20, 2021, 16:04

It seems to me that meerkat trying to icinga check a service (at least) which is no longer there is somehow poisoning the in-memory cache or breaking it somehow in a way which cannot be recovered from.

Steps to Reproduce:
1. Create a meerkat dashboard which includes a director service on a director host
2. View the dashboard
3. Delete the host in director and deploy pending changes in director
(The meerkat diagram will lose the checks over the next 20 seconds or so, Card => "UNKNOWN", Arrows and SVGs disappear)
4. Re-add the hosts in director (e.g. check for changes in the Sync Rule and Trigger a Run, deploy pending changes)
(The meerkat diagram will not regain those checks despite them re-appearing in Icinga)

5. Work-around is Restart the Meetkat containers, e.g.
`root@TBSP-Docker1:/opt/docker/stacks/narwhal/tbs.reportal.broadcastservices.cloud# docker-compose -p narwhal_tbs restart`
 
Observations:
- icinga api response was fine after step 4
- meerkat api response to check_state was empty json {} after step 3
- after step 4 meerkat "edit" view can see the services when e.g. creating/editing elements but gets the "UNKNOWN"/blank response the same as "view" view

**Comment by s2156945** [comment]
Have also seen this with Host Filters / locking on "Invalid" which was also fixed by a restart of the docker-compose
