### ISSUE TITLE
Read last check result directly from the object

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#62]
In GitLab by @ollytom on Feb 16, 2022, 13:49

I can't make merge requests for this repository, but here's a patch which does a minor tidy up of the backend which should hopefully help in troubleshooting #62 . Change tested ok in a local meerkat environment.

[0001-Read-last-check-result-directly-from-the-object.patch](https://my-gitlab-bucket.s3.amazonaws.com/508115840/849671907b6a11e57c70b2e3fe266e6f3c66841b3bd3506b17474861ff445790/0001-Read-last-check-result-directly-from-the-object.patch)

To apply the patch, download the file and run `git am $file` from within the repository directory.

**Comment by afoster** [comment]
@ollytom can you make a PR now? Patch link above is no longer available.

**Comment by afoster** [comment]
Sorry, found it. Raised https://github.com/meerkat-dashboard/meerkat/pull/75 for re-review
