### ISSUE TITLE
Maintain project website next to source code?

### ISSUE THREAD

**Issue by ollytom** [meerkat-dashboard/meerkat#79]
See there's a new repository https://github.com/meerkat-dashboard/meerkat-website
Rather than having a separate repository - which itself has its own branch "gh-pages" - what about
keeping the website in the (empty) docs directory here?
This is what Github's introduction advises on https://pages.github.com
Keeping it in one place means updating the documenation/website can be done alongside
adding/fixing/features etc.

**Comment by davekempe** [comment]
Agreed. My noobness is the only explanation

**Comment by ollytom** [comment]
Oh pff come on @davekempe you and me both.
I saw your post on the icinga mailing list, then saw the new repository, then looked up how Github pages even works because I have NFI.
