### ISSUE TITLE
Duplicate info in docs/index.md and README

### ISSUE THREAD

**Issue by ollytom** [meerkat-dashboard/meerkat#82]
What should be where? As a rule of thumb I'd say stuff relevant to meerkat development lives in the README. Stuff for a regular users is published to the project website.

Roughly, the README could contain the sections:

* Intro (short. "Meerkat is...", screenshots, obfuscated photo of real dashboards on real screens!)
* Quick start (just a link to the project website)
* Development (how to compile, test)
* Support (link to sol1 website etc.)
* Contributing
* License

The website could contain everything else.
Here's a non-exhaustive list:

* Intro (long. include intro from README, then expand. why does the project exist? who is it for? goals?)
* Installation from a package (tarball, deb, container image, helm chart, chocolatey, whatever!)
* Usage reference (element types etc.)
* Configuration reference
* Development (link to source repository, with README)

**Comment by davekempe** [comment]
agreed, I had written the website content from the readme, then I realised I should have diverged them a bit.

**Comment by MC-brunomendes** [comment]
If you just do 
`docker build -t meerkat .`
`docker run meerkat`

you get 
2022/08/10 07:47:49 /root/backend/main.go:93: Error initializing dashboards directory - mkdir dashboards: permission denied


I don't really think the install steps or even docker run is that simple to follow

**Comment by davekempe** [comment]
hey @MC-brunomendes thanks for the feedback. We are currently refactoring the docs into the docs/ directory and expect to have some better install instructions with tested steps shortly.

**Comment by ollytom** [comment]
Thoughts? https://ollytom.github.io/meerkat/
Inspired by documentation of Go, Django projects and Stripe's docs

**Comment by davekempe** [comment]
> Thoughts? https://ollytom.github.io/meerkat/ Inspired by documentation of Go, Django projects and Stripe's docs

Its great! Nice work. Lets use it. This is exactly what I had in mind
