### ISSUE TITLE
ACK label added to unmatched regex default value

### ISSUE THREAD

**Issue by sol1-matt** [meerkat-dashboard/meerkat#86]
When creating an icinga card with a regex match default value, so it behaves both like a icinga card check (state) and label (static text), the default value is post pended with `(ACK)` if the worst state is acknowledged. 

This is not ideal if the text is intended to be a LABEL and the STATE is transmitted thorough background color

**Comment by sol1-matt** [comment]
The labels wanted here are FLEX and HARRIS
![image](https://user-images.githubusercontent.com/17868735/178624419-370cb07d-f466-4328-8d2d-535dfdd8bb54.png)

**Comment by davekempe** [comment]
I think this needs some more digging @sol1-matt and perhaps a little clearer explanation of what you want to do. I didn't quite understand after reading it twice.

**Comment by sol1-matt** [comment]
A text label on card elements by default is displaying the text of the **STATE**, eg: `WARNING`,  `CRITICAL`, `OK`. When the check **STATE** is acknowledged `(ACK)` is post pended based to the status string , eg: `WARNING (ACK)`. 

There is a feature that allows for the card element to display regex extracted **VALUE** OR a defined default **VALUE** if the regex doesn't match that isn't the text value of the status as can be seen in the screen shot above. 

Both the usage of **STATE** and **VALUE** on card elements are part of Meerkat's existing functionality.

The problem is that `(ACK)`, part of the **STATE** string, gets post pended to the regex/default **VALUE** string. 

The requested feature is the ability to supress the post pending of the `(ACK)` state string for check card elements when the displayed text is from a **VALUE** and not the **STATE**.

**Comment by ollytom** [comment]
Are we aware of any users where appending "(ACK)" is relied upon
or useful?

**Comment by sol1-matt** [comment]
> Are we aware of any users where appending "(ACK)" is relied upon or useful?

I believe (ACK) was added by request.
We want to preserve this functionality for **STATE** strings, but not value string
OR we make it a boolean

**Comment by ollytom** [comment]
> I believe (ACK) was added by request.

Ah damn ok fair enough. Was hoping I could delete some code haha ;)
