### ISSUE TITLE
Allow user to select between Hard and Soft state for Element change

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#88]
Currently, Meerkat changes when the soft state changes. This is nosier than it should be, and means that dashboards can flap too much. 

Please add a feature where we can select whether we want a meerkat element to change on hard or soft state. This data is already present in the UI, just need to plumb in the option and go from there. 

This setting should be available in the Advanced Options for a card, SVG and image elements.
I think it should default to Hard state actually, not Soft State like it does now.

**Comment by davekempe** [comment]
For more information see the state_type defined here: https://icinga.com/docs/icinga-2/latest/doc/09-object-types/#service
I don't see a reference to checking it in the code.

**Comment by ollytom** [comment]
A default of hard state seems appropriate. That's the way icinga itself is designed, right? Notifications are only sent in a hard state?

**Comment by davekempe** [comment]
Confirmed @ollytom default hard state is more correct. If users want quicker dashboard changes, they can adjust the hard state settings using retry_interval on a service for example or max_check_attempts to 0 even.

**Comment by ollytom** [comment]
> If users want quicker dashboard changes, they can adjust the 
> hard state settings using retry_interval on a service for example or max_check_attempts to 0 even.

Ok cool. Thanks! It's hard to find the place where the hard/soft state would be propagated to the dashboard.

There are no less than 3 different API calls to get hosts/services/etc. Each have their own slightly different interface (different combo of URL paths vs query params) and each then does their own little transformation to custom data types different from the Icinga API itself !! Ahh!! But I'll get there!!!

**Comment by ollytom** [comment]
Resolved by c6b31546d11a
