### ISSUE TITLE
Error decoding Icinga2 API response: unmarshaltypeerror

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#89]
After upgrading to latest Meerkat (with the https://github.com/meerkat-dashboard/meerkat/pull/75) changes, I get this error in the logs and some objects don't render correctly. Performance data doesn't come through and I get 503s in the web interface.

```
Jul 27 15:23:01 icinga-master meerkat[366115]: 2022/07/27 15:23:01 /root/meerkat/backend/icinga.go:221: Error decoding Icinga2 API response: %!w(*json.UnmarshalTypeError=&{object 0x82bac0 36482 checkResult results.attrs.last_check_result.performance_data})
Jul 27 15:23:01 icinga-master meerkat[366115]: 2022/07/27 15:23:01 /root/meerkat/backend/icinga.go:149: Cache retrieval failed: %!w(*json.UnmarshalTypeError=&{object 0x82bac0 36482 checkResult results.attrs.last_check_result.performance_data})
```

**Comment by ollytom** [comment]
I reverted the change as it's a breaking change. More logic is
required when parsing responses from the Icinga API to account for
objects with performance data and command fields set to either type
string or []string (array of strings).

I've already dealt with this with Icinga (in Go) before:
https://git.sr.ht/~otl/icinga/tree/master/item/service.go.
It's not hard (approx. 14 lines of code).

**Comment by ollytom** [comment]
Thanks for filing this issue, by the way, it uncovered a whole  bunch of incorrect error handling and logging!
Now the error messages print correctly, which helped me debug this issue. Example error message was something like "unable to marshal icingaObject field PerfData type string into []string"

See commit e6383a1
